language: minimal
branches:
  only:
    - develop
git:
  depth: false
services:
  - docker
install:
  - PROJECT_NAME=harnic
before_script:
  - sed -ri s/-image_label-/${TRAVIS_BRANCH}-${TRAVIS_BUILD_NUMBER}-${TRAVIS_COMMIT}/ Dockerfile
script:
  - stty cols 120
  - travis_fold start "docker_build" && docker build . -t ${PROJECT_NAME} && travis_fold end "docker_build"
  - travis_fold start "run_as_job" && docker run ${PROJECT_NAME} --help && docker run -v `pwd`:/hars ${PROJECT_NAME} harnic/hars/tests/test1_a.har harnic/hars/tests/test1_b.har
